### ISSUE TITLE
Get misses all the time

### ISSUE THREAD

**Issue by rafaelcapucho** [openresty/srcache-nginx-module#22]
Hello,

I installed the nginx 1.4.1 with patch applyed but i'm still getting errors.

No matter what I do I ever get "get misses".

http://pastebin.com/raw.php?i=NNgFAwRK

Thank you :)

**Comment by kapouer** [comment]
Ouch, got bitten by this as well. Could you add a reference to set-misc-nginx-module and set_md5 somewhere in the srcache README please ?

**Comment by agentzh** [comment]
@kapouer Mind to submit a pull request for the doc addition?
