### ISSUE TITLE
Redis cache not working

### ISSUE THREAD

**Issue by gabrielarrais** [openresty/srcache-nginx-module#31]
Hi,

I'm following your exemple of redis caching and I'm not having always MISS as result.
I'm using openresty/1.7.2.1 .

This is my config, I omitted some values of it because they contain our company data.

```
   location /redis {

        internal  ;
        set_md5  $redis_key $args;
        redis_pass  redis-endpoint.com:6379;

    }
    location /redis2 {

        internal  ;
        set_unescape_uri  $exptime $arg_exptime;
        set_unescape_uri  $key $arg_key;
        set_md5  $key;
        redis2_query  set $key $echo_request_body;
        redis2_query  expire $key $exptime;
        redis2_pass  redis-endpoint.com:6379;

    }
    location ~ ^/ {         
        add_header XXXX;
        proxy_set_header  XXXX;
        set  $key $host$request_uri;
        default_type  text/css;
        srcache_response_cache_control  off;
        srcache_ignore_content_encoding  on;
        set_escape_uri  $escaped_key $key;
        srcache_fetch  GET /redis $key;
        srcache_store  PUT /redis2 key=$escaped_key&exptime=1500;
        proxy_pass  http://upstream;
        proxy_set_header  Host                           $host;
        proxy_read_timeout  300s;
        proxy_set_header  User-Agent                     $http_user_agent;
        proxy_pass_header  Set-Cookie;
        proxy_pass_header  X-Track;
        proxy_pass_header  P3P;
        add_header  Cache-Control no-cache;
        add_header  X-Cache-Status $srcache_fetch_status;
        access_log  /var/log/nginx/access.log access-log;

    }
```

Intermittently, when I send a request to the "srcached" location, I receive in the error log two messages like these:

2014/08/19 18:36:24 [error] 11188#0: *603 srcache_fetch: cache sent invalid status line while sending to client, client: xx.xx.xx.xx, server: , request: "GET / HTTP/1.1", subrequest: "/redis", upstream: "http://xx.xx.xx.xx:80/redis?www.hostname.com./param=value", host: "www.hostname.com"

2014/08/19 18:36:24 [error] 11188#0: *603 srcache_fetch: cache sent truncated response body while sending to client, client: xx.xx.xx.xx, server: , request: "GET / HTTP/1.1", subrequest: "/redis", upstream: "http://xx.xx.xx.xx:80/redis?www.hostname.com./param=value", host: "www.hostname.com"

Can you help me?

Thanks in advance!

**Comment by base698** [comment]
Also, having a problem with getting this to work, works fine with memcached.  I've seen two errors, but this is the current one:  
_2016/08/24 08:11:28 [error] 33527#0: *4 open() "/usr/local/nginx/html/redis" failed (2: No such file or directory), client: 127.0.0.1, server: , request: "GET /users/3 HTTP/1.1", subrequest: "/redis", host: "localhost"_

The key is making it into redis and the response looks ok there.  I was getting originally a similar error described here about truncated response.

```
      location = /redis {
          #internal ;
          set $redis_key $args;
          set_md5  $redis_key;
          redis2_query get $redis_key
          redis2_pass  redis;
      }

      location = /redis2 {
          internal ;
          set_unescape_uri  $exptime $arg_exptime;
          set_unescape_uri  $key $arg_key;
          set_md5  $key;
          redis2_query  set $key $echo_request_body;
          redis2_query  expire $key $exptime;
          redis2_pass  redis;
      }

       location /users {
          set $key "cache:$http_authorization:$request_uri";
          default_type  text/css;
          srcache_response_cache_control  off;
          srcache_ignore_content_encoding  on;
          set_escape_uri  $escaped_key $key;
          srcache_fetch  GET /redis $key;
          srcache_store  PUT /redis2 key=$escaped_key&exptime=1500;
          proxy_pass  http://backend;
       }
```

Banging my head against a wall.

**Comment by agentzh** [comment]
@base698 You should use `redis_pass` in your `location = /redis` instead of `redis2_pass`. Please read the corresponding document more carefully:

https://github.com/openresty/srcache-nginx-module#caching-with-redis

**Comment by agentzh** [comment]
@base698 BTW, better join and post to the openresty-en mailing list instead unless you are very sure that it is ngx_srcache's bug.  Please see http://openresty.org/en/community.html for more details.

Additionally commenting on a closed issue is a bad idea nevertheless. Thanks for your cooperation.
