### ISSUE TITLE
srcache_store subrequest failed

### ISSUE THREAD

**Issue by kevinycm** [openresty/srcache-nginx-module#33]
Hi, 
        我目前正在使用openresty 1.7.7.1，逻辑如下：request的uri得到缓存key，先判断这个key在memcached集群中是否有对应的response，如果没有，则通过proxy_pass转到backend_api，得到backend_api的结果然后当作response返回给client，同时store到memcached集群．这样的话，下次同样的request过来之后，直接就可以从memcached获取response．
　　但现在在线上运行一段时间之后，得到的错误信息如下：
　　 srcache_store subrequest failed: rc=502 status=0 while sending to client, client: xxx.xxx.xxx.xxx, server: xxx.com, request: "GET /test?code=W7WSoSBZOIM HTTP/1.1", subrequest: "/memc", host: "xxx.com"

nginx的配置如下：
upstream memc_backend {
    hash $arg_key consistent;
    server 127.0.0.1:11211;
    server 127.0.0.1:11212;
    server 127.0.0.1:11213;
    server 127.0.0.1:11214;
    keepalive 1024;
}
server {
　　location = /memc {
　　　　internal;
　　　　memc_connect_timeout 100ms;
　　　　memc_send_timeout 100ms;
　　　　memc_read_timeout 100ms;
　　　　memc_ignore_client_abort on;
　　　　set $memc_key $arg_key;
　　　　set $memc_exptime $arg_exptime;
　　　　memc_pass memc_backend;
　　}

　　location = /test {
        set_by_lua_file $key conf/lua/test/k_get_cache_key.lua;
        if ($http_is_update_cache = "Yes") {
            srcache_fetch DELETE /memc key=$key;
        }
        set $exptime 3600;
        srcache_fetch GET /memc key=$key;
        srcache_store PUT /memc key=$key&exptime=$exptime;
        proxy_pass http://backend_api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $x_remote_addr;
        proxy_set_header Host $proxy_host;
        proxy_set_header Range $http_range;
        proxy_set_header X-NginX-Proxy true;
    }
}　　      
能帮忙看下原因么？我已经查了一段时间了，还是没有头绪～～

**Comment by agentzh** [comment]
@kevinycm Please, no Chinese here. This place is supposed to be English only. If you really want to use Chinese, please join the openresty (Chinese) mailing list instead:

http://openresty.org/#Community

Regarding your question, it seems that your memcached server or something on the network link in between is aborting the connection occasionally. I believe there should be a more detailed error message before that message you pasted. Are you seeing any other errors in your nginx's error log file?

**Comment by kevinycm** [comment]
Sorry, @agentzh ，no Chinese here，my mistake．so according to your suggestion,  it seems that there should be some other error message in my nginx's error log and they are the reason why my service doesn't work.I will focus on that, Thanks very much.
