### ISSUE TITLE
srcache  cant work with nginx slice option not stored

### ISSUE THREAD

**Issue by davidka79** [openresty/srcache-nginx-module#40]
Hello
sorry I cant memcached requests
I need to slice responce from upstream by slice 1m;

server {
        listen       front.network;
        server_name  cdn.cdntest.com;

         location = /memc {
             internal;
             memc_connect_timeout 100ms;
             memc_send_timeout 100ms;
             memc_read_timeout 100ms;
             memc_ignore_client_abort on;
             set $memc_key $query_string;
             set $memc_exptime 3600;

             memc_pass ram1;
         }

         location / {
             slice  1m;

             set $key $uri$is_args$args$slice_range;
             #set $key $uri$args$slice_range;
             srcache_fetch GET /memc $key;
             srcache_store PUT /memc $key;

             srcache_store_ranges on;
             srcache_store_statuses 200 206 301 302;
             srcache_ignore_content_encoding on;

             proxy_set_header  Range $slice_range;
             proxy_pass http://www.cdntest.com;
         }
     }

but in error.log I got
srcache_store: skipped because response body truncated: 149616567 > 1048576 while sending to client

**Comment by agentzh** [comment]
@davidka79 No, ngx_srcache does not work with the `slice` directive at all.

**Comment by davidka79** [comment]
Hello
Sorry for long response. Thank you for your message, I got it now :(
