### ISSUE TITLE
using standalone upstream keepalive module ?

### ISSUE THREAD

**Issue by chipitsine** [openresty/srcache-nginx-module#46]
do we actually need it here ?

https://github.com/openresty/srcache-nginx-module/blob/master/util/build.sh#L44

nginx supports builtin upstream keepalive

**Comment by agentzh** [comment]
No, we don't need it any more.

**Comment by chipitsine** [comment]
it seems some tests need to be rewritten

https://travis-ci.org/chipitsine/srcache-nginx-module/builds/132612641#L1609

**Comment by agentzh** [comment]
Not rewriting tests, but patch ngx_http_redis! :)

OpenResty has custom patches for this module too, to allow the use of Nginx variables in redis_pass.

**Comment by chipitsine** [comment]
I use util/build.sh, so it should apply all patches

**Comment by agentzh** [comment]
@chipitsine Nope, `util/build.sh` only applies nginx core patches atm.

**Comment by agentzh** [comment]
@chipitsine Please see below for more details about OpenResty's patches for ngx_http_redis:

https://github.com/openresty/openresty/blob/master/util/mirror-tarballs#L445

**Comment by agentzh** [comment]
@chipitsine Because this ticket is really about upstream keepalive module, I'm afraid we should continue the discussion somewhere else.
