### ISSUE TITLE
how to properly build/patch this module ?

### ISSUE THREAD

**Issue by chipitsine** [openresty/srcache-nginx-module#49]
there's util/build.sh, which, I suppose must do all the dirty work.
however, it seems there are extra patches, where can I find documentation how to apply them ?

currently, build fails with ... https://travis-ci.org/chipitsine/srcache-nginx-module/builds/134990770#L1604

**Comment by chipitsine** [comment]
it seems that util/build.sh does not fail when patch is missing

https://travis-ci.org/chipitsine/srcache-nginx-module/builds/135003274#L478

should we rewrite it with '&&' ?

**Comment by agentzh** [comment]
@chipitsine As I've mentioned before, the ngx_http_redis module requires two patches from the OpenResty repo:

https://github.com/openresty/openresty/blob/master/util/mirror-tarballs#L459

The `util/build.sh` script only handles patches for the nginx core only, not 3rd-party modules like ngx_http_redis (yet).

**Comment by agentzh** [comment]
@chipitsine Okay, I was wrong. The `util/build.sh` script of this project actually tries to handle ngx_http_redis module's patching itself.

I've fixed the `util/build.sh` script to croak when the ngx_http_redis patch is not found. Thanks for the report!
