### ISSUE TITLE
srcache vs. proxy_cache

### ISSUE THREAD

**Issue by es** [openresty/srcache-nginx-module#51]
What's the advantage of using `srcache` vs. the `proxy_cache` directive?

**Comment by agentzh** [comment]
@es The former allows distributed non-file-based caching.

**Comment by es** [comment]
Is the storage mechanism the only reason to use `srcache`? I imagine it'd be possible to use the `memcached` module to get similar functionality with `proxy_cache`.

**Comment by agentzh** [comment]
@es Yes, you can surely use srcache to replace proxy_cache. You were asking about "advantages".

**Comment by es** [comment]
Thanks for the clarification.
