### ISSUE TITLE
compute a $storeKey for srcache_store after upstream response ?

### ISSUE THREAD

**Issue by kapouer** [openresty/srcache-nginx-module#52]
Hi,
i'm trying to implement HTTP Vary with srcache.
A typical upstream response will contain a `Vary: Accept-Language` field,
`header_filter_by_lua_block` could then

1. compute a $storeKey by concatenation of key/value of request fields listed in that Vary header
2. store url => Vary field in a shared dict
(Upon later request, `set_by_lua_block` could compute a $requestKey by looking up
in the shared dict to get the list of Vary headers for the requested url.)

Question: is it possible to make srcache_store use $storeKey and not preprocessed key ?

**Comment by agentzh** [comment]
@kapouer I think so.

**Comment by kapouer** [comment]
[Got it !](https://github.com/kapouer/cache-protocols/blob/master/tag/index.conf#L53-L61)
