### ISSUE TITLE
Storing > 1MB objects in memcached is actually possible

### ISSUE THREAD

**Issue by kapouer** [openresty/srcache-nginx-module#54]
Typically with `memcached -I 10m`.
It seems to also require nginx `client_max_body_size 10M;`, or else i get
```
client intended to send too large body: 1222117 bytes, client: 127.0.0.1, server: , request: "GET /css/semantic.css HTTP/1.1", subrequest: "/_memc", host: "localhost:3001", referrer: "http://localhost:3001/"
```

**Comment by agentzh** [comment]
@kapouer Oh, thanks for the tip! Will you please create a pull request to leave this tip in the docs? Many thanks!
