### ISSUE TITLE
Might be an error in the redis example

### ISSUE THREAD

**Issue by larssn** [openresty/srcache-nginx-module#56]
Hi

Should the line `redis_pass 127.0.0.1:6379;`
be `redis2_pass 127.0.0.1:6379;` ?

We've been testing with the first variant, but not sure if its optimal.

**Comment by agentzh** [comment]
@larssn No, there's no typo here. In the `srcache_fetch` subrequest, you can only use the ngx_redis module instead of the ngx_redis2 module since the latter returns the raw Redis server response while the former returns the decoded user data.

**Comment by larssn** [comment]
Ah, great to know. Thanks for a good plugin!
