### ISSUE TITLE
example using srcache with php-fpm

### ISSUE THREAD

**Issue by vishalred** [openresty/srcache-nginx-module#58]
Hi,

We are tying to use srcache with php-fpm .  Please advice if you have any reference we can use for our implementation.

Thank you,
Vishal

**Comment by agentzh** [comment]
@vishalred Have you seen the official documentation of this module?

https://github.com/openresty/srcache-nginx-module/#readme

Nginx does not really care what's behind `fastcgi_pass` BTW as long as that thing speaks the FastCGI protocol.

**Comment by vishalred** [comment]
@agentzh  thank you for the update.

my config is not working for some reason. Do u have a tutorial or example code I can use as a ref ?

Thankyou,
Vishal

**Comment by agentzh** [comment]
Have you read the doc carefully? It has a lot of examples. It also has tips on debugging issues in your configuration.
