### ISSUE TITLE
upstream_http_content_type not working with srcache_store_skip

### ISSUE THREAD

**Issue by ledzepp4eva** [openresty/srcache-nginx-module#67]
Hey,
I'm trying to use the Content-Type in the http response header to decide if content should be cached or not, but however the variable is returning the wrong value
<pre>
     set $key $scheme$host$request_uri$http_range$http_accept_encoding;
     set_by_lua $skip '
        if ngx.var.upstream_http_content_type == "image/jpeg" then
          return 1
        end
        return 0
        ';
     srcache_fetch GET /memc $key;
     srcache_store PUT /memc $key;
     srcache_store_statuses 200 206 301;
     srcache_store_ranges on;
     srcache_store_max_size 1M;
     srcache_fetch_skip  $skip;
     srcache_store_skip  $skip;
</pre>

However when logging this information using the log format

<pre>'"$skip" ' '"$upstream_http_content_type" '</pre>

I get back

<pre>
"0" "image/jpeg"
</pre>

I'm trying to work out why this return 0 and not 1, does it have something to do when srcache_*_skip is processed like before the response header, so it will always give back the default value?

Thanks,
Liam

**Comment by agentzh** [comment]
@ledzepp4eva You confused the timing order. The `set_by_lua` directive runs *before* nginx sends a request to the upstream, while the `$upstream_http_content_type` variable reads the *response* header *after* nginx receives the response header from the upstream (and thus way after nginx sends the request to the upstream).

**Comment by ledzepp4eva** [comment]
@agentzh thank you for your reply. I have been testing this again using the map module instead.

<pre>
map $upstream_http_content_type $skip {
  default 0;
#  ~text/javascript 0;
#  ~application/json 0;
#  ~font/* 0;
  ~image/* 1;
#  ~text/css 0;
}
</pre>

Which works fine, when the content-type is `image/jpeg` the `$skip` variable is set to 1 as expected, however when I enable the two lines of code:
<pre>
     srcache_fetch_skip  $skip;
     srcache_store_skip  $skip;
</pre>

Suddenly the variable of the `$skip` variable is now 0.  Sorry if I've misunderstood your response but if the variable is already being set by the map I wouldn't think those 2 srcache directives would change this?

Thank you for response.
Liam

**Comment by ledzepp4eva** [comment]
Sorry so my problem was the use of
`srcache_fetch_skip $skip`
When this is disabled and I only use store it works as I was expecting it to work.
I can then disable my backend and the images still load. 

I assume the `srcache_fetch_skip` is being run before the response header? Sorry for all the silly questions.

Liam

**Comment by agentzh** [comment]
@ledzepp4eva Yes, srcache_fetch_skip runs right after the access phase, which is also before nginx sends requests to the upstream. I suggest you read the documentation more carefully. See

https://github.com/openresty/srcache-nginx-module/#srcache_fetch_skip

Note the line "post-access".

To learn more about nginx request processing phases, please refer to the nginx tutorials below:

https://openresty.org/download/agentzh-nginx-tutorials-en.html

**Comment by ledzepp4eva** [comment]
Thank you. Will have a read of this today.
