### ISSUE TITLE
srcache conflict with set-cookie header

### ISSUE THREAD

**Issue by hqweiyu** [openresty/srcache-nginx-module#70]
Recently I developed an application with php framework called Laravel, which will return set-cookie in every page. But I found that there is a conflict when return the response with set-cookie header, i wanna know if there is a way to solve this problem？

![image](https://user-images.githubusercontent.com/3405076/34100435-5abe782e-e41d-11e7-8d8d-b81efe7e0ad6.png)

**Comment by agentzh** [comment]
@hqweiyu Ignoring the `Set-Cookie` header when doing caching is a clear violation of the HTTP standard RFC.

**Comment by hqweiyu** [comment]
@agentzh thanks.
