### ISSUE TITLE
can't use srcache_store twice in the same location block

### ISSUE THREAD

**Issue by hqweiyu** [openresty/srcache-nginx-module#71]
Hi,
This is how it goes, I need to set two cache in redis, one (cache A) is designed to return normal page response and will be expired in 15 minutes, and i will refresh cache A when expired. And the other one (cache B) is designed to be stored in redis permanently, and when the backend is shutdown, nginx will return cache B. Cache B will be refreshed when the backend service is available.
The problem is how can I set two cache in the same location block？
![image](https://user-images.githubusercontent.com/3405076/34155022-b70f776a-e4f2-11e7-89e3-861ea8f48b38.png)

**Comment by agentzh** [comment]
@hqweiyu No, this is not supported by this module without hacks or tricks.

**Comment by hqweiyu** [comment]
@agentzh So what's your thoughts in designing this?

**Comment by agentzh** [comment]
@hqweiyu I suggest you use OpenResty's Lua module for this.
