### ISSUE TITLE
In function ‘ngx_http_srcache_response_no_cache’

### ISSUE THREAD

**Issue by wu1045** [openresty/srcache-nginx-module#99]
/data/tmp/srcache-nginx-module-0.32/src/ngx_http_srcache_util.c: In function ‘ngx_http_srcache_response_no_cache’:
/data/tmp/srcache-nginx-module-0.32/src/ngx_http_srcache_util.c:558:39: error: request for member ‘elts’ in something not a structure or union
     ccp = r->headers_out.cache_control.elts;
                                       ^
/data/tmp/srcache-nginx-module-0.32/src/ngx_http_srcache_util.c:564:49: error: request for member ‘nelts’ in something not a structure or union
     for (i = 0; i < r->headers_out.cache_control.nelts; i++) {
                                                 ^
make[1]: *** [objs/addon/src/ngx_http_srcache_util.o] Error 1
make[1]: Leaving directory `/data/tmp/nginx-1.23.2'
make: *** [build] Error 2

**Comment by zhuizhuhaomeng** [comment]
The module does not support nginx 1.23.
PR is welcomed.

**Comment by kapouer** [comment]
Isn't it already fixed in latest https://github.com/openresty/srcache-nginx-module/commit/be22ac0dcd9245aadcaca3220da96a0c1a0285a7 commit ?
Maybe it's time for a release :)

**Comment by fanpiao** [comment]
我也遇到了这个问题，可以修复下吗

**Comment by agentzh** [comment]
It was already fixed in ngx_srcache v0.33. Consider it resolved.
